-- Step 0: Add Dallas to office check constraint
ALTER TABLE projects DROP CONSTRAINT projects_office_check;
ALTER TABLE projects ADD CONSTRAINT projects_office_check CHECK (office IN ('Austin', 'San Antonio', 'Corpus Christi', 'Dallas'));

-- Step 1: Insert project row (required before blocks due to foreign key)
INSERT INTO "public"."projects" ("id", "title", "description", "category", "phase", "latitude", "longitude", "start_date", "completion_date", "office", "total_hours", "is_confidential", "accent_color", "created_at", "updated_at", "created_by") VALUES ('X26-RB01', 'Midland Furniture Pilot', 'Classroom FFE survey analysis from a one-semester furniture pilot across 4 Midland ISD campuses, comparing student and teacher preferences across chairs and desks', 'campus-life', 'Completed', '31.99730000', '-102.07790000', '2025-09-01', '2026-02-07', 'Dallas', '20', 'false', '#B5BD00', now(), now(), null);

-- Step 2: Insert blocks
INSERT INTO project_blocks (id, project_id, block_type, block_order, data) VALUES

('x26-rb01-section-intro', 'X26-RB01', 'section', 1, $${"title": "Midland ISD Classroom Furniture Pilot"}$$::jsonb),

('x26-rb01-stat-grid', 'X26-RB01', 'stat-grid', 2, $${"columns": 4, "stats": [{"label": "Students Surveyed", "value": "321", "detail": "Across 4 campuses", "trend": "neutral"}, {"label": "Teachers Surveyed", "value": "7", "detail": "4 pilot classrooms", "trend": "neutral"}, {"label": "Positive First Impressions", "value": "93%", "detail": "Curious or excited about the new furniture", "trend": "up"}, {"label": "Overall Chair Comfort", "value": "92.5%", "detail": "Students rated their chair comfortable", "trend": "up"}]}$$::jsonb),

('x26-rb01-text-overview', 'X26-RB01', 'text-content', 3, $${"content": "## Survey Overview\n\nPfluger Architects partnered with Midland ISD to run a one-semester classroom furniture pilot across four campuses: Midland High School, Lee High School, Midland Freshman High School, and Lee Freshman High School. All 321 students received the same chair and desk options. Each of the four classrooms received a different teacher desk and chair setup.\n\nFurniture was labeled Chair 1–4 and Desk 1–4 to keep responses product-neutral and focused on features rather than brand preference.\n\n**Data note:** A survey typo listed \"Desk 3\" twice in the student questionnaire. All student desk preference data labeled \"Desk 3\" reflects combined votes for what were actually Desk 3 and Desk 4. Teacher desk data is unaffected.\n\n## Next Steps\n\nFindings will be presented at the Sample Rodeo event in May, where Midland ISD stakeholders will use the data to inform furniture customization decisions for the full school build-out."}$$::jsonb),

('x26-rb01-timeline', 'X26-RB01', 'timeline', 4, $${"layout": "horizontal", "events": [{"date": "Fall 2025", "title": "Pilot Semester", "description": "One-semester furniture pilot across 4 classrooms", "status": "complete"}, {"date": "Feb 3, 2026", "title": "Theme Review", "description": "Initial qualitative theme review with R&B team", "status": "complete"}, {"date": "Feb 6, 2026", "title": "Insights Review", "description": "Updated findings reviewed with Wendy, presented to Interiors group", "status": "complete"}, {"date": "Feb 7, 2026", "title": "Midland Presentation", "description": "Findings presented to Midland ISD", "status": "complete"}, {"date": "May 2026", "title": "Sample Rodeo", "description": "Broader stakeholder presentation to inform final furniture selections", "status": "pending"}]}$$::jsonb),

('x26-rb01-section-students', 'X26-RB01', 'section', 5, $${"title": "Student Findings", "sources": [1, 2]}$$::jsonb),

('x26-rb01-feedback-students', 'X26-RB01', 'feedback-summary', 6, $${"positives": {"title": "What Students Love", "score": 93, "themes": [{"theme": "Comfort", "mentions": 137, "description": "Most cited reason for choosing a favorite chair"}, {"theme": "Size & Space", "mentions": 48, "description": "Wide seats and larger desks with room to work"}, {"theme": "Mobility", "mentions": 21, "description": "Easy to move and rearrange for group work"}, {"theme": "Backpack Hook", "mentions": 20, "description": "Chair 1 — 20% of its fans specifically mention the hook"}]}, "concerns": {"title": "What Needs Work", "score": 62, "themes": [{"theme": "Desk Size", "mentions": 49, "description": "Most common desk complaint — desks need to be bigger"}, {"theme": "Caster Control", "mentions": 48, "description": "Desks either roll too freely or not enough"}, {"theme": "Seat Comfort", "mentions": 18, "description": "Some chairs uncomfortable for longer periods"}, {"theme": "Height", "mentions": 15, "description": "Standard heights do not fit all body types"}, {"theme": "Durability", "mentions": 8, "description": "Some desks feel unbalanced or unstable"}, {"theme": "Surface Transfer", "mentions": 4, "description": "Light-colored surfaces pick up pencil marks"}]}}$$::jsonb),

('x26-rb01-product-chairs-students', 'X26-RB01', 'product-options', 7, $${"columns": 4, "showSpecs": true, "lines": [{"name": "Chair 1", "subtitle": "20.1% preferred", "options": [{"name": "Chair 1", "price": 0, "color": "#00A9E0", "specs": [{"label": "Students preferred", "value": "20.1%"}, {"label": "Comfort rating", "value": "96.4%"}, {"label": "Can sit most/all class", "value": "91.1%"}, {"label": "Standout feature", "value": "Backpack hook"}]}]}, {"name": "Chair 2", "subtitle": "16.1% preferred", "options": [{"name": "Chair 2", "price": 0, "color": "#67823A", "specs": [{"label": "Students preferred", "value": "16.1%"}, {"label": "Comfort rating", "value": "93.3%"}, {"label": "Can sit most/all class", "value": "97.8%"}, {"label": "Standout feature", "value": "No gap in seat"}]}]}, {"name": "Chair 3", "subtitle": "Student Favorite — 46.6%", "options": [{"name": "Chair 3", "price": 0, "color": "#9A3324", "specs": [{"label": "Students preferred", "value": "46.6%"}, {"label": "Comfort rating", "value": "90.0%"}, {"label": "Can sit most/all class", "value": "89.2%"}, {"label": "Standout feature", "value": "Wide and spacious"}]}]}, {"name": "Chair 4", "subtitle": "17.2% preferred", "options": [{"name": "Chair 4", "price": 0, "color": "#F2A900", "specs": [{"label": "Students preferred", "value": "17.2%"}, {"label": "Comfort rating", "value": "93.8%"}, {"label": "Can sit most/all class", "value": "87.5%"}, {"label": "Standout feature", "value": "Lightweight and mobile"}]}]}]}$$::jsonb),

('x26-rb01-product-desks-students', 'X26-RB01', 'product-options', 8, $${"columns": 3, "showSpecs": true, "lines": [{"name": "Desk 1", "subtitle": "30.0% preferred", "options": [{"name": "Desk 1", "price": 0, "color": "#00A9E0", "specs": [{"label": "Students preferred", "value": "30.0%"}, {"label": "Key theme", "value": "Familiar size, easy to move"}]}]}, {"name": "Desk 2", "subtitle": "17.3% preferred", "options": [{"name": "Desk 2", "price": 0, "color": "#67823A", "specs": [{"label": "Students preferred", "value": "17.3%"}, {"label": "Key theme", "value": "Compact, stackable"}]}]}, {"name": "Desk 3 + Desk 4", "subtitle": "Top Pick — 52.7% combined*", "options": [{"name": "Desk 3 + Desk 4", "price": 0, "color": "#9A3324", "specs": [{"label": "Students preferred", "value": "52.7% (combined)"}, {"label": "Size cluster", "value": "~35% — spacious work surface"}, {"label": "Mobility cluster", "value": "~17% — lockable wheels"}, {"label": "Note", "value": "Survey typo combined Desk 3 and Desk 4 votes"}]}]}]}$$::jsonb),

('x26-rb01-quotes-students', 'X26-RB01', 'quotes', 9, $${"columns": 2, "quotes": [{"text": "because it is wide and also big for a person", "author": "Student #1, Midland Freshman"}, {"text": "it gives me more room to work on, like if I am doing a poster I can put my whole poster on it", "author": "Student V19"}, {"text": "the wheels are lockable, they will not move around", "author": "Student #244, Midland Freshman"}, {"text": "it moves easily bc of the wheels on every side of it", "author": "Student #14, Midland Freshman"}, {"text": "they are too tall for the short people", "author": "Student #3, Midland Freshman"}, {"text": "because its not connected to a desk and its comfortable", "author": "Student #23, Midland Freshman"}, {"text": "leave transfer marks from our pencils", "author": "Student #60, Lee HS"}, {"text": "it has a hook and is comfortable", "author": "Chair 1 fan, Midland Freshman"}]}$$::jsonb),

('x26-rb01-section-teachers', 'X26-RB01', 'section', 10, $${"title": "Teacher Findings", "sources": [3, 4]}$$::jsonb),

('x26-rb01-feedback-teachers', 'X26-RB01', 'feedback-summary', 11, $${"positives": {"title": "What Teachers Love", "score": 80, "themes": [{"theme": "Lightweight Student Chairs", "mentions": 3, "description": "Top priority for teachers — easy to reset the room"}, {"theme": "Overall Upgrade", "mentions": 4, "description": "4 of 5 teachers said it is a nice upgrade over old furniture"}, {"theme": "Backpack Hook", "mentions": 2, "description": "Two teachers independently called out Chair 1 hook as valuable"}, {"theme": "Mobile Table", "mentions": 2, "description": "Used as podium and movable teaching station by T5 and T6"}]}, "concerns": {"title": "What Needs Work", "score": 55, "themes": [{"theme": "Too Many Casters", "mentions": 3, "description": "More casters makes desks harder to control and move in bulk"}, {"theme": "Desk Size", "mentions": 2, "description": "Some desks too large, stick out into walkways"}, {"theme": "Mobile Table Bulk", "mentions": 2, "description": "Too heavy and wide to maneuver comfortably during class"}, {"theme": "Surface Transfer", "mentions": 1, "description": "Light surface transfers pencil marks through paper"}, {"theme": "Storage Lock", "mentions": 1, "description": "Wardrobe lock gets stuck and is loud"}]}}$$::jsonb),

('x26-rb01-product-teacher-prefs', 'X26-RB01', 'product-options', 12, $${"columns": 3, "showSpecs": true, "lines": [{"name": "Chair 4", "subtitle": "Top teacher pick for students", "options": [{"name": "Chair 4", "price": 0, "color": "#F2A900", "specs": [{"label": "Teachers who prefer", "value": "T2, T3 (2 of 5)"}, {"label": "Why", "value": "Lightweight, easy to move, quiet on floors"}]}]}, {"name": "Chair 1", "subtitle": "Runner-up for students", "options": [{"name": "Chair 1", "price": 0, "color": "#00A9E0", "specs": [{"label": "Teachers who prefer", "value": "T6, T7 (2 of 5)"}, {"label": "Why", "value": "Wide, stable, backpack hook"}]}]}, {"name": "2 Casters", "subtitle": "Preferred desk configuration", "options": [{"name": "2 Casters", "price": 0, "color": "#67823A", "specs": [{"label": "Teachers who prefer", "value": "T2, T3, T6 (3 of 5)"}, {"label": "Why", "value": "Balance between mobile and stable"}, {"label": "Who rearranges desks", "value": "Teachers in 4 of 5 classrooms"}]}]}]}$$::jsonb),

('x26-rb01-quotes-teachers', 'X26-RB01', 'quotes', 13, $${"columns": 2, "quotes": [{"text": "I have loved it and will be so sad when it is gone", "author": "T5"}, {"text": "I do not want to see the old chairs anymore", "author": "T6"}, {"text": "Chaotic with all different student pieces but I really like the teacher pieces", "author": "T3"}, {"text": "Steer away from bulky and heavy pieces", "author": "T3"}, {"text": "So many casters means it makes it hard to actually move the desks around", "author": "T5"}, {"text": "Some of the others are way too big and stick out on the sides", "author": "T3"}]}$$::jsonb),

('x26-rb01-text-conclusion', 'X26-RB01', 'text-content', 14, $${"content": "## Design Recommendations\n\n**Size matters most.** 45% of students prioritize workspace size when choosing a favorite desk or chair. Larger surfaces and wider seats are the primary driver of preference.\n\n**Two casters is the sweet spot.** Teachers do the majority of rearranging (4 of 5 classrooms). Their preference is 2 casters — enough mobility to reset the room without desks rolling during class.\n\n**Height adjustability is worth considering.** About 10% of students mentioned height as a pain point. Adjustable-height options accommodate the full range of student body types without requiring multiple SKUs.\n\n**Specify darker laminate.** Multiple students and teachers noted pencil transfer on light-colored surfaces. A darker or more durable laminate solves this at the material level.\n\n**Keep the hook.** Chair 1 backpack hook was called out by 20% of its fans and two teachers independently. A small feature with outsized perceived value.\n\n---\n\nThank you to Wendy Rosamond and the Midland ISD team for piloting this program and providing such detailed feedback. These findings will directly shape furniture specifications for the full school build-out."}$$::jsonb),

('x26-rb01-sources', 'X26-RB01', 'sources', 15, $${"sources": [{"id": 1, "title": "MHS LHS FFE Classroom Pilot, Fall 2025 — Student Survey Questions", "author": "Midland ISD"}, {"id": 2, "title": "MHS LHS FFE Classroom Pilot, Fall 2025 — Student Survey Responses (321 responses)", "author": "Midland ISD"}, {"id": 3, "title": "MHS LHS FFE Classroom Pilot, Fall 2025 — Teacher Survey Questions", "author": "Midland ISD"}, {"id": 4, "title": "MHS LHS FFE Classroom Pilot, Fall 2025 — Teacher Survey Responses (7 responses)", "author": "Midland ISD"}]}$$::jsonb);
