-- RAG field updates for X26-RB01 (Midland Furniture Pilot)
-- Generated 2026-02-18
-- Skips pure section headers: x26-rb01-section-intro, x26-rb01-section-students, x26-rb01-section-teachers

UPDATE project_blocks SET
  summary = $$Key pilot statistics: 321 students and 7 teachers surveyed across 4 Midland ISD campuses, with 93% reporting positive first impressions and 92.5% rating their chair comfortable.$$,
  tags = '{"FFE","furniture pilot","Midland ISD","student survey","teacher survey","statistics","comfort","first impressions","chairs","desks"}',
  searchable_text = $$321 students surveyed across 4 campuses. 7 teachers surveyed in 4 pilot classrooms. 93% of students had a positive first impression, curious or excited about the new furniture. 92.5% of students rated their chair comfortable.$$,
  conclusions = '{"321 students and 7 teachers participated in the Midland ISD furniture pilot across 4 campuses","93% of students were curious or excited about the new furniture","92.5% of students rated their chair comfortable"}'
WHERE id = 'x26-rb01-stat-grid';

UPDATE project_blocks SET
  summary = $$Overview of the survey methodology and pilot structure across four Midland ISD campuses, covering furniture labeling, a data note on the Desk 3 survey typo, and plans for the Sample Rodeo presentation in May 2026.$$,
  tags = '{"FFE","furniture pilot","Midland ISD","survey methodology","Midland High School","Lee High School","Midland Freshman High School","Lee Freshman High School","Sample Rodeo","desk survey","data note","product-neutral"}',
  searchable_text = $$Pfluger Architects partnered with Midland ISD to run a one-semester classroom furniture pilot across four campuses: Midland High School, Lee High School, Midland Freshman High School, and Lee Freshman High School. All 321 students received the same chair and desk options. Each of the four classrooms received a different teacher desk and chair setup. Furniture was labeled Chair 1-4 and Desk 1-4 to keep responses product-neutral and focused on features rather than brand preference. A survey typo listed Desk 3 twice in the student questionnaire. All student desk preference data labeled Desk 3 reflects combined votes for what were actually Desk 3 and Desk 4. Teacher desk data is unaffected. Findings will be presented at the Sample Rodeo event in May 2026, where Midland ISD stakeholders will use the data to inform furniture customization decisions for the full school build-out.$$,
  conclusions = '{"Pilot ran across 4 campuses: Midland High School, Lee High School, Midland Freshman High School, and Lee Freshman High School","Furniture was labeled 1-4 to keep responses feature-focused rather than brand-focused","A survey typo combined Desk 3 and Desk 4 votes in student data; teacher desk data is unaffected","Findings will be presented at the Sample Rodeo event in May 2026 to inform final furniture selections"}'
WHERE id = 'x26-rb01-text-overview';

UPDATE project_blocks SET
  summary = $$Project timeline for X26-RB01, from the Fall 2025 pilot semester through February 2026 presentations to Midland ISD, with the Sample Rodeo stakeholder event planned for May 2026.$$,
  tags = '{"FFE","furniture pilot","Midland ISD","timeline","milestones","Sample Rodeo","presentation","R&B team","Interiors group"}',
  searchable_text = $$Fall 2025: One-semester furniture pilot across 4 classrooms, complete. February 3, 2026: Theme Review, initial qualitative theme review with R&B team, complete. February 6, 2026: Insights Review, updated findings reviewed with Wendy and presented to Interiors group, complete. February 7, 2026: Midland Presentation, findings presented to Midland ISD, complete. May 2026: Sample Rodeo, broader stakeholder presentation to inform final furniture selections, pending.$$,
  conclusions = '{"The furniture pilot ran during Fall 2025 across 4 classrooms","Findings were reviewed with the R&B team and Interiors group before being presented to Midland ISD on February 7, 2026","A Sample Rodeo stakeholder presentation is planned for May 2026 to inform final furniture selections"}'
WHERE id = 'x26-rb01-timeline';

UPDATE project_blocks SET
  summary = $$Student feedback themes from the pilot: top positives were comfort, size, mobility, and the backpack hook; top concerns were desk size, caster control, seat comfort, height fit, durability, and pencil mark transfer on light surfaces.$$,
  tags = '{"student feedback","comfort","size","mobility","backpack hook","desk size","casters","height adjustability","durability","surface transfer","FFE","furniture pilot","qualitative themes"}',
  searchable_text = $$Student satisfaction score: 93%. What students love: Comfort, 137 mentions, most cited reason for choosing a favorite chair. Size and space, 48 mentions, wide seats and larger desks with room to work. Mobility, 21 mentions, easy to move and rearrange for group work. Backpack hook, 20 mentions, 20% of Chair 1 fans specifically mention the hook. What needs work: Desk size, 49 mentions, most common desk complaint, desks need to be bigger. Caster control, 48 mentions, desks either roll too freely or not enough. Seat comfort, 18 mentions, some chairs uncomfortable for longer periods. Height, 15 mentions, standard heights do not fit all body types. Durability, 8 mentions, some desks feel unbalanced or unstable. Surface transfer, 4 mentions, light-colored surfaces pick up pencil marks. Concern score: 62%.$$,
  conclusions = '{"Comfort was the most cited reason for choosing a favorite chair with 137 mentions","Desk size was the top student complaint at 49 mentions; desks need to be bigger","Caster control was close behind at 48 mentions; desks roll too freely or not enough","The backpack hook on Chair 1 drove 20% of its preference votes","Height was mentioned 15 times; standard heights do not fit all body types"}'
WHERE id = 'x26-rb01-feedback-students';

UPDATE project_blocks SET
  summary = $$Student chair preference breakdown: Chair 3 was the clear favorite at 46.6% for its wide and spacious design, followed by Chair 1 (20.1%), Chair 4 (17.2%), and Chair 2 (16.1%), with comfort ratings and sit-duration scores for each.$$,
  tags = '{"student chair preference","Chair 1","Chair 2","Chair 3","Chair 4","comfort rating","backpack hook","wide seat","spacious","lightweight","mobility","FFE","furniture pilot","Midland ISD"}',
  searchable_text = $$Chair 1: 20.1% of students preferred. Comfort rating 96.4%. 91.1% can sit most or all of class. Standout feature: backpack hook. Chair 2: 16.1% of students preferred. Comfort rating 93.3%. 97.8% can sit most or all of class. Standout feature: no gap in seat. Chair 3: 46.6% of students preferred, student favorite. Comfort rating 90.0%. 89.2% can sit most or all of class. Standout feature: wide and spacious. Chair 4: 17.2% of students preferred. Comfort rating 93.8%. 87.5% can sit most or all of class. Standout feature: lightweight and mobile.$$,
  conclusions = '{"Chair 3 was the student favorite at 46.6%, chosen primarily for its wide and spacious design","Chair 3 had the largest preference margin but the lowest comfort rating at 90.0%; size drove preference over comfort","Chair 1 had the highest comfort rating at 96.4% despite being only the second most preferred overall","Chair 2 had the highest sit-duration score at 97.8%; most students could sit in it most or all of class","Chair 4 was valued for being lightweight and mobile"}'
WHERE id = 'x26-rb01-product-chairs-students';

UPDATE project_blocks SET
  summary = $$Student desk preference data: Desk 3 and Desk 4 combined received 52.7% due to a survey typo, Desk 1 received 30.0%, and Desk 2 received 17.3%. Key sub-themes within the Desk 3/4 group were spacious work surface and lockable wheels.$$,
  tags = '{"student desk preference","Desk 1","Desk 2","Desk 3","Desk 4","casters","lockable wheels","work surface","spacious","stackable","FFE","furniture pilot","survey typo"}',
  searchable_text = $$Desk 1: 30.0% of students preferred. Key theme: familiar size, easy to move. Desk 2: 17.3% of students preferred. Key theme: compact, stackable. Desk 3 and Desk 4 combined: top pick at 52.7% combined due to a survey typo that listed Desk 3 twice in the student questionnaire. Within that cluster, approximately 35% chose for spacious work surface and approximately 17% chose for lockable wheels.$$,
  conclusions = '{"Desk 3 and Desk 4 combined received 52.7% of student preference votes due to a survey typo in the student questionnaire","Within the Desk 3/4 cluster, approximately 35% preferred for spacious work surface and 17% for lockable wheels","Desk 1 was the clear standalone preference at 30.0%, valued for familiar size and ease of movement","Desk 2 was the least preferred at 17.3%, valued for compact and stackable design"}'
WHERE id = 'x26-rb01-product-desks-students';

UPDATE project_blocks SET
  summary = $$Direct student quotes from the pilot capturing preferences around wide seating, large work surfaces, wheel mobility, height concerns, pencil mark transfer on light surfaces, and the backpack hook.$$,
  tags = '{"student quotes","wide seat","desk size","casters","lockable wheels","height","pencil marks","surface transfer","backpack hook","mobility","comfort","FFE","student voice"}',
  searchable_text = $$Student quote: because it is wide and also big for a person. Student number 1, Midland Freshman. Student quote: it gives me more room to work on, like if I am doing a poster I can put my whole poster on it. Student V19. Student quote: the wheels are lockable, they will not move around. Student number 244, Midland Freshman. Student quote: it moves easily because of the wheels on every side of it. Student number 14, Midland Freshman. Student quote: they are too tall for the short people. Student number 3, Midland Freshman. Student quote: because its not connected to a desk and its comfortable. Student number 23, Midland Freshman. Student quote: leave transfer marks from our pencils. Student number 60, Lee HS. Student quote: it has a hook and is comfortable. Chair 1 fan, Midland Freshman.$$,
  conclusions = '{"Students valued wide seating and large desk surfaces for project work","Lockable wheels were specifically valued to prevent desks from rolling during class","Height was a noted concern; standard heights do not accommodate shorter students","Light-colored desk surfaces transfer pencil marks through paper","The backpack hook on Chair 1 was valued for convenience and comfort combined"}'
WHERE id = 'x26-rb01-quotes-students';

UPDATE project_blocks SET
  summary = $$Teacher feedback themes: top positives were lightweight student chairs, overall upgrade over old furniture, the backpack hook, and the mobile table; top concerns were too many casters, oversized desks, mobile table bulk, pencil mark transfer, and a loud storage lock.$$,
  tags = '{"teacher feedback","lightweight chairs","casters","mobile table","backpack hook","desk size","surface transfer","storage lock","FFE","furniture pilot","classroom management"}',
  searchable_text = $$Teacher satisfaction score: 80%. What teachers love: Lightweight student chairs, 3 mentions, top priority for teachers, easy to reset the room. Overall upgrade, 4 mentions, 4 of 5 teachers said it is a nice upgrade over old furniture. Backpack hook, 2 mentions, two teachers independently called out Chair 1 hook as valuable. Mobile table, 2 mentions, used as podium and movable teaching station by teachers T5 and T6. What needs work: Too many casters, 3 mentions, more casters makes desks harder to control and move in bulk. Desk size, 2 mentions, some desks too large and stick out into walkways. Mobile table bulk, 2 mentions, too heavy and wide to maneuver comfortably during class. Surface transfer, 1 mention, light surface transfers pencil marks through paper. Storage lock, 1 mention, wardrobe lock gets stuck and is loud. Concern score: 55%.$$,
  conclusions = '{"Lightweight student chairs were the top teacher priority for easy classroom reset","4 of 5 teachers rated the new furniture as a nice upgrade over their previous furniture","Teachers prefer fewer casters on desks; more casters makes bulk movement harder to control","Some desks are too large and stick out into walkways, impeding classroom flow","The mobile table was valued as a podium but was too heavy and wide for comfortable maneuvering during class"}'
WHERE id = 'x26-rb01-feedback-teachers';

UPDATE project_blocks SET
  summary = $$Teacher product preferences: Chair 4 was the top pick for student chairs (lightweight, quiet on floors), Chair 1 was the runner-up (wide, stable, backpack hook), and 2 casters was the preferred desk configuration for balancing mobility and stability.$$,
  tags = '{"teacher preferences","Chair 1","Chair 4","casters","desk configuration","lightweight","mobility","stability","FFE","furniture pilot","classroom reset","classroom management"}',
  searchable_text = $$Chair 4 was the top teacher pick for student chairs. Teachers T2 and T3 preferred Chair 4, 2 of 5 teachers. Reason: lightweight, easy to move, quiet on floors. Chair 1 was the runner-up for student chairs. Teachers T6 and T7 preferred Chair 1, 2 of 5 teachers. Reason: wide, stable, backpack hook. 2 casters was the preferred desk configuration. Teachers T2, T3, and T6 preferred 2 casters, 3 of 5 teachers. Reason: balance between mobile and stable. Teachers rearrange desks in 4 of 5 classrooms.$$,
  conclusions = '{"Teachers preferred Chair 4 for students due to its lightweight design and quiet movement on floors","Chair 1 was the teacher runner-up, valued for width, stability, and the backpack hook","3 of 5 teachers preferred 2 casters on desks as the best balance between mobility and control","Teachers rearrange desks in 4 of 5 classrooms, making desk mobility a practical daily priority"}'
WHERE id = 'x26-rb01-product-teacher-prefs';

UPDATE project_blocks SET
  summary = $$Direct teacher quotes expressing strong enthusiasm for the new furniture overall, with specific concerns about bulky and heavy pieces, excessive casters making desks harder to move, and oversized desks sticking out into walkways.$$,
  tags = '{"teacher quotes","furniture preference","casters","desk size","lightweight","mobility","FFE","classroom management","furniture pilot","teacher voice"}',
  searchable_text = $$Teacher quote: I have loved it and will be so sad when it is gone. Teacher T5. Teacher quote: I do not want to see the old chairs anymore. Teacher T6. Teacher quote: Chaotic with all different student pieces but I really like the teacher pieces. Teacher T3. Teacher quote: Steer away from bulky and heavy pieces. Teacher T3. Teacher quote: So many casters means it makes it hard to actually move the desks around. Teacher T5. Teacher quote: Some of the others are way too big and stick out on the sides. Teacher T3.$$,
  conclusions = '{"Teachers expressed strong positive sentiment about the new furniture overall","Teacher T3 specifically recommended steering away from bulky and heavy pieces","Excessive casters make it harder to move desks in bulk according to Teacher T5","Larger desk sizes were flagged as a concern for classroom walkway clearance by Teacher T3","Teacher sentiment was strongly positive for teacher furniture and mixed for student furniture"}'
WHERE id = 'x26-rb01-quotes-teachers';

UPDATE project_blocks SET
  summary = $$Design recommendations derived from the pilot: prioritize workspace size, specify 2 casters on desks, consider height adjustability, use darker laminate to prevent pencil transfer, and include the backpack hook in chair specifications.$$,
  tags = '{"design recommendations","FFE","workspace size","casters","height adjustability","laminate","backpack hook","durability","Midland ISD","furniture specifications","campus life"}',
  searchable_text = $$Design recommendations for Midland ISD furniture selection. Size matters most: 45% of students prioritize workspace size when choosing a favorite desk or chair. Larger surfaces and wider seats are the primary driver of preference. Two casters is the sweet spot: teachers do the majority of rearranging in 4 of 5 classrooms. Their preference is 2 casters, enough mobility to reset the room without desks rolling during class. Height adjustability is worth considering: about 10% of students mentioned height as a pain point. Adjustable-height options accommodate the full range of student body types without requiring multiple SKUs. Specify darker laminate: multiple students and teachers noted pencil transfer on light-colored surfaces. A darker or more durable laminate solves this at the material level. Keep the hook: Chair 1 backpack hook was called out by 20% of its fans and two teachers independently. A small feature with outsized perceived value. These findings will directly shape furniture specifications for the full school build-out.$$,
  conclusions = '{"45% of students prioritize workspace size, making larger surfaces and wider seats the primary driver of preference","2 casters is the recommended desk configuration: mobile enough to reset rooms but stable during class","Height adjustability is recommended to accommodate all student body types without requiring multiple SKUs","Darker or more durable laminate is recommended to prevent pencil transfer marks on desk surfaces","The backpack hook was cited by 20% of Chair 1 fans and two teachers independently; it should be included in specifications"}'
WHERE id = 'x26-rb01-text-conclusion';

UPDATE project_blocks SET
  summary = $$Data sources for the Midland ISD furniture pilot: student survey questions and responses (321 responses) and teacher survey questions and responses (7 responses), all collected by Midland ISD during Fall 2025.$$,
  tags = '{"sources","Midland ISD","student survey","teacher survey","FFE","data sources","Fall 2025","MHS","LHS"}',
  searchable_text = $$Source 1: MHS LHS FFE Classroom Pilot, Fall 2025, Student Survey Questions, authored by Midland ISD. Source 2: MHS LHS FFE Classroom Pilot, Fall 2025, Student Survey Responses, 321 responses, authored by Midland ISD. Source 3: MHS LHS FFE Classroom Pilot, Fall 2025, Teacher Survey Questions, authored by Midland ISD. Source 4: MHS LHS FFE Classroom Pilot, Fall 2025, Teacher Survey Responses, 7 responses, authored by Midland ISD.$$,
  conclusions = '{"All survey data was collected by Midland ISD during Fall 2025","321 students and 7 teachers responded to the pilot surveys","Data comes from the MHS (Midland High School) and LHS (Lee High School) FFE classroom pilot"}'
WHERE id = 'x26-rb01-sources';
